### PR TITLE
Improve CleanerBotA's wheel inertias

### PR DESCRIPTION
**Pull request by chapulina**
### Fixed bug

The inertias were too big for the wheels, resulting in jerky movement.

Before:

cleanerbot_inertia

After:

image

Just the wheels, after:

image

### Fix applied

Calculated new inertias based on a sphere of radius 0.1 m and mass of 5 kg.

The same change was applied to the version 2 of this model: 

https://app.ignitionrobotics.org/OpenRobotics/fuel/models/CleanerBot1

### CODE REVIEW

**Review by aaronchongth — APPROVED** [review]
Thanks for fixing this, @chapulina! Tested and working well in `airport_terminal` world. Could you help with signing your commit? We will be able to merge it then

**Comment by chapulina** [comment]
> Could you help with signing your commit?

I think it was already signed, right? I just rebased onto `main`

**Comment by aaronchongth** [comment]
:wave: Thanks! Apologies, I meant GPG signed.

**Comment by chapulina** [comment]
Ahh gotcha, signed!

**Pull request merged**
