### PR TITLE
A home world with delivery and looping tasks

### PR DESCRIPTION
**Pull request by KamalanathanN**
Signed-off-by: KamalanathanN <31615486+KamalanathanN@users.noreply.github.com>

Hi , i have configed the TinyRobot for this home world sim i hope you guys like it :)

i'm attempting to integrate a TinyCleaner in shape of a roomba inside this world for cleaning task as the current cleaners are not suited in home environment. i tried to reskin the create2 sdf with roomba and added soltcar plugin it spawned fine inside gazebo but has some error when launched with RMF. Once that's fixed i'll update the world.

### CODE REVIEW

**Comment by Yadunund** [comment]
Thanks for this contribution. Some high level comments to address first:
* Remove the new icons folder. Since you're re-using the icons from `rmf_dashboard_resources/office`, you can let the config know to look for the `office` folder to find the same icons. We don't want to have duplicates in this repo
* Suggest to replace `home_world` with `home` to be consistent with the other maps
* Is the `home_world.png` something you created from scratch or modified? If it is taken without modification from somewhere, what license is associated with it?

**Comment by KamalanathanN** [comment]
@Yadunund  sorry i messed up the PR again 😒 😞
I'll open new one with suggested changes.


> * Is the `home_world.png` something you created from scratch or modified? If it is taken without modification from somewhere, what license is associated with it?

The png file is from [here](https://www.nicepng.com/ourpic/u2t4o0i1i1e6y3i1_craftsman-style-house-plan-large-catholic-family-home/), 
```License | Personal Use```
from reading the description below image, i think its ok to use it here. 
Let me know if it needs to be modified.

**Comment by Yadunund** [comment]
You don't have to close the PR. You can push changes to the same one.

**Comment by KamalanathanN** [comment]
@Yadunund Actually the PR changes were signed off incorrectly. I tried reverting and recommit with proper sign here [bda9e68](https://github.com/open-rmf/rmf_demos/pull/146/commits/bda9e68aeb694e1cce8f9dcc8df460e6b2817583). still it showed previous commits were not signed.
sorry for the noob mistake 😅
i've reforked and made signed commits with suggested changes. Looks like its not reflected in this PR. is there a workaround or 
may i close this PR and open new?

**Pull request closed without merging**
