### PR TITLE
Add M&L demo to rmf_demos

### PR DESCRIPTION
**Pull request by mdfesto**
* updated "RMF" text to "Open-RMF"
* added new Manufacturing & Logistics demo
* separated out some standalone feature demo examples into a new category

Signed-off-by: Matthew Festo <matthew@openrobotics.org>

### CODE REVIEW

**Review by mdfesto — COMMENTED** [review]
Corrected some errors in the M&L video link and some further updates of "RMF" to "Open-RMF"

**Review by mdfesto — COMMENTED** [review]
added DCO commit

**Review by mdfesto — COMMENTED** [review]
removing incorrect signoff

**Review by akash-roboticist — APPROVED** [review]

**Review by mdfesto — COMMENTED** [review]
updating signing

**Review by mxgrey — APPROVED** [review]

**Pull request merged**
