### PR TITLE
Added instructions to change `server_uri` when using `rmf-web` dashboard

### PR DESCRIPTION
**Pull request by aaronchongth**
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

## Documentation

Adding the instruction to target the `server_uri` launch parameter when using the web dashboard.

### CODE REVIEW

**Comment by Yadunund** [comment]
Not sure if I'm missing something but I don't see the `server_uri` argument defined in any of the launch files or passed as a Param into the adapters?

**Comment by mayman99** [comment]
@Yadunund the `server_uri` is the `fleet_adapter` launch file.

**Review by mayman99 — APPROVED** [review]

**Comment by Yadunund** [comment]
@mayman99 i'm aware but the argument is only defined in the [launch file](https://github.com/open-rmf/rmf_ros2/blob/7ed2196c37edc444ba065847b399c73891f4d681/rmf_fleet_adapter/launch/fleet_adapter.launch.xml#L43) in the `rmf_fleet_adapter` library 

But all these adapters that control the robots in the simulation here have [these](https://github.com/open-rmf/rmf_demos/blob/65c45a1f52c5d909381373b35df4146d4069e7f5/rmf_demos/launch/include/adapters/tinyRobot_adapter.launch.xml#L12) launch files in the `rmf_demos` package that include the above launch file and overwrite the relevant parameters. But as you can see, the `server_uri` parameter is not explicitly set from any argument that can be overwritten by the demo launch files.

My issue is with how the `server_uri` parameter values makes it all the way from [rmf_demos_ign/office.launch.xml](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_ign/launch/office.launch.xml) -> [rmf_demos/offcie.launch.xml](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos/launch/office.launch.xml) -> [tinyRobot_adapter](https://github.com/open-rmf/rmf_demos/blob/65c45a1f52c5d909381373b35df4146d4069e7f5/rmf_demos/launch/office.launch.xml#L18-L22) without any of these launch files defining an `  <arg name="server_uri"/>` element? Do undefined parameters just automatically get passed as a ROS 2 parameter to every node in the launch file?

**Comment by mayman99** [comment]
> My issue is with how the server_uri parameter values makes it all the way from [rmf_demos_ign/office.launch.xml](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_ign/launch/office.launch.xml) -> [rmf_demos/offcie.launch.xml](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos/launch/office.launch.xml) -> [tinyRobot_adapter](https://github.com/open-rmf/rmf_demos/blob/65c45a1f52c5d909381373b35df4146d4069e7f5/rmf_demos/launch/office.launch.xml#L18-L22) without any of these launch files defining an <arg name="server_uri"/> element? Do undefined parameters just automatically get passed as a ROS 2 parameter to every node in the launch file?

Yeah I think this is the case. I remember it actually took me a while to figure out that `server_uri` parameter when I first started using `rmf`, maybe we could refactor it's usage to be a bit more obvious, e.g. move it to higher level launch files, or chain it using `arg` elements in the launch files.

**Comment by aaronchongth** [comment]
Yup! We had this discussion on slack as well, turns out this might be an intended behavior. I think I will go ahead and merge this for now

**Pull request merged**
